### ISSUE TITLE
Ionic 4 sample?

### ISSUE THREAD

**Issue by jadbox** [yannbf/ionic-lottie#5]
I'm wondering if this same technique can be used for Ionic v4?

**Comment by RembrandtDiaz** [comment]
I have tried. No luck.  Have you been able to implement it?

**Comment by jadbox** [comment]
I've looked into it, but had to make the decision to go with React for my team for our current project as there were also other libs we needed that where only available for React.

**Comment by coli21** [comment]
> I'm wondering if this same technique can be used for Ionic v4?

Yes. Follow the docs and you'll be fine.

**Comment by sek** [comment]
@coli21 I had this working in Ionic 3, but applying same thing in Ionic 4 (angular 7), get the following:

    Can't bind to 'options' since it isn't a known property of 'lottie-animation-view'.

any tips?
